#!/usr/bin/env node
/**
 * Plugin scaffolding CLI — `node scripts/new-plugin.mjs <name>`
 *
 * Generates a new first-party Cordis plugin package in `packages/plugin-<name>`
 * and wires it into the monorepo:
 *   1. creates packages/plugin-<name>/ (src/index.ts + package.json + tsconfig.json)
 *   2. adds `@agent-harness/plugin-<name>` to packages/core dependencies
 *      (workspace:* — required for the loader's dynamic import() to resolve)
 *   3. appends an entry to cordis.patch.yml
 *
 * After scaffolding, run `pnpm install` and the plugin will load via its
 * package name, exactly like @agent-harness/plugin-hello.
 *
 * Usage:
 *   node scripts/new-plugin.mjs weather
 *   # → packages/plugin-weather, @agent-harness/plugin-weather
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const NAME = process.argv[2]
if (!NAME) {
  console.error('usage: node scripts/new-plugin.mjs <name>   (e.g. weather → @agent-harness/plugin-weather)')
  process.exit(1)
}
if (!/^[a-z0-9][a-z0-9-]*$/.test(NAME)) {
  console.error(`invalid plugin name "${NAME}": use lowercase letters, digits and dashes only (start with a letter/digit)`)
  process.exit(1)
}

const pkgName = `@agent-harness/plugin-${NAME}`
const dir = join(ROOT, 'packages', `plugin-${NAME}`)

if (existsSync(dir)) {
  console.error(`directory already exists: packages/plugin-${NAME}`)
  process.exit(1)
}

// ---- 1. package skeleton ----
mkdirSync(join(dir, 'src'), { recursive: true })

const indexTs = `/**
 * ${pkgName} — a first-party Cordis plugin.
 *
 * Generated by \`scripts/new-plugin.mjs\`. It follows the pure-Cordis contract
 * (only \`cordis\` is imported — no harness-private services), so it can be
 * loaded both by this harness and by any other Cordis-4 runtime.
 *
 * Edit this file to implement your plugin. The scaffold provides a small
 * service (\`ctx.${NAME}\`) plus an example: anything returned from
 * \`ctx.${NAME}.ping()\` is logged on load and on demand.
 */

import { Context, Service } from 'cordis'

declare module 'cordis' {
  interface Context {
    ${NAME}: ${NAME[0].toUpperCase()}${NAME.slice(1)}Service
  }
}

export interface ${NAME[0].toUpperCase()}${NAME.slice(1)}Options {
  /** Message printed when the service starts. */
  greeting?: string
}

export class ${NAME[0].toUpperCase()}${NAME.slice(1)}Service extends Service {
  private readonly greeting: string

  constructor(ctx: Context, options: ${NAME[0].toUpperCase()}${NAME.slice(1)}Options = {}) {
    super(ctx, '${NAME}')
    this.greeting = options.greeting ?? 'hello from ${pkgName}'
  }

  /** Example method: callable from other plugins via \`ctx.${NAME}.ping()\`. */
  ping(): string {
    this.ctx.logger('${NAME}').info(this.greeting)
    return this.greeting
  }
}

export default (ctx: Context, options: ${NAME[0].toUpperCase()}${NAME.slice(1)}Options = {}) => {
  ctx.plugin(${NAME[0].toUpperCase()}${NAME.slice(1)}Service, options)
}
`

const pkgJson = JSON.stringify(
  {
    name: pkgName,
    version: '0.1.0',
    description: `First-party Cordis plugin for agent-harness (${NAME})`,
    type: 'module',
    license: 'MIT',
    main: 'src/index.ts',
    types: 'src/index.ts',
    exports: { '.': './src/index.ts' },
    scripts: { typecheck: 'tsc --noEmit' },
    dependencies: { cordis: '^4.0.0-rc.8' },
    devDependencies: {
      '@types/node': '^22.0.0',
      typescript: '^5.9.0',
      tsx: '^4.20.0',
    },
  },
  null,
  2,
) + '\n'

const tsconfig = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      lib: ['ES2022'],
      types: ['node'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      noEmit: true,
    },
    include: ['src/**/*'],
  },
  null,
  2,
) + '\n'

writeFileSync(join(dir, 'src', 'index.ts'), indexTs)
writeFileSync(join(dir, 'package.json'), pkgJson)
writeFileSync(join(dir, 'tsconfig.json'), tsconfig)
console.log(`created packages/plugin-${NAME}/ (src/index.ts, package.json, tsconfig.json)`)

// ---- 2. register in packages/core dependencies ----
const corePkgPath = join(ROOT, 'packages', 'core', 'package.json')
const corePkg = JSON.parse(readFileSync(corePkgPath, 'utf8'))
if (corePkg.dependencies?.[pkgName]) {
  console.log(`core already depends on ${pkgName} — skipping`)
} else {
  corePkg.dependencies = { [pkgName]: 'workspace:*', ...corePkg.dependencies }
  writeFileSync(corePkgPath, JSON.stringify(corePkg, null, 2) + '\n')
  console.log(`added "${pkgName}": "workspace:*" to packages/core dependencies`)
}

// ---- 3. append to cordis.patch.yml ----
const patchPath = join(ROOT, 'cordis.patch.yml')
if (existsSync(patchPath)) {
  const patch = readFileSync(patchPath, 'utf8')
  if (patch.includes(`'@agent-harness/plugin-${NAME}'`) || patch.includes(`name: '@agent-harness/plugin-${NAME}'`)) {
    console.log('cordis.patch.yml already references this plugin — skipping')
  } else {
    const entry = `\n- insert:\n    - id: ${NAME}\n      name: '${pkgName}'\n      config: {}\n`
    writeFileSync(patchPath, patch.replace(/\s*$/, '') + entry)
    console.log(`appended entry to cordis.patch.yml (id: ${NAME})`)
  }
} else {
  console.warn('cordis.patch.yml not found — skipped patch registration')
}

console.log('\nnext steps:')
console.log('  pnpm install')
console.log(`  pnpm -C packages/plugin-${NAME} run typecheck`)
console.log('  then run the harness with any config that includes cordis.patch.yml')
